apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:

  replicas: 2 # Running 2 replicas for high availability
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      
        - name: flask-app
          image: flask-devops-app

        
          # IMPORTANT: Replace YOUR_DOCKER_USERNAME with your actual Docker Hub username
          
          ports:
            - containerPort: 5000
          env:
            - name: GREETING
              value: "I was deployed by Kubernetes!" # Overriding the default greeting

          # ✨ To IMPRESS, mention these in your video as a key improvement
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5