apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app # This MUST match the 'app' label in your Deployment
  ports:
    - protocol: TCP
    
      port: 80 # The port to access the service from outside the cluster
      targetPort: 5000 # The port your container is listening on